# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.





title: Alex Evetts
baseurl: ""
favicon: "/images/favicon.ico"

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # Options: "air", "aqua", "contrast", "dark", "dirt", "neon", "sunrise"

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache # Recommended for Minimal Mistakes speed


category_archive:
  type: liquid
  path: /blog/


include:
  - assets
  - images

defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: true

author:
  # name   : "Alex Evetts"
  avatar : "/images/profilepic.jpg" # Optional
  bio    : "Data, Mathematics, AI"
  # location: "United Kingdom"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:aevetts@hotmail.co.uk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/aevetts"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/alex-evetts-a9a93a1aa"
    - label: "arXiv"
      icon: "ai ai-arxiv"
      url: "https://arxiv.org/a/evetts_a_1.html"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.co.uk/citations?user=qezpNbwAAAAJ&hl=en&oi=ao"
    - label: "orcid"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0002-2252-8661"



footer:
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url:
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url:
    # - label: "Feed"
    #   icon: "fas fa-fw fa-rss-square"
    #   url: # Leave this blank or delete this specific block